version: '2'
services:
  ebs-contacts:
    build: ebs-contacts
    image: ebs-contacts
    ports:
      - 3001:3000
    environment:
      HOST: '0.0.0.0'

  ebs-shell:
    build: ebs-shell
    image: ebs-shell
    ports:
      - 3000:80
