version: '2'
services:
  ebs-contacts:
    build: ebs-contacts
    image: ebs-contacts
    networks:
      - local-network
    ports:
      - 3002:3002
    environment:
      HOST: '0.0.0.0'

  ebs-settings:
    build: ebs-settings
    image: ebs-settings
    networks:
      - local-network
    ports:
      - 3003:3003
    environment:
      HOST: '0.0.0.0'

  ebs-tam:
    build: ebs-tam
    image: ebs-tam
    networks:
      - local-network
    ports:
      - 3004:3004
    environment:
      HOST: '0.0.0.0'

  ebs-shell:
    build: ebs-shell
    image: ebs-shell
    networks:
      - local-network
    ports:
      - 3001:80

  ebs-proxy:
    build: ebs-proxy
    image: ebs-proxy
    ports:
      - 3000:80
    networks:
      - local-network
    depends_on:
      - ebs-contacts
      - ebs-settings
      - ebs-tam
      - ebs-shell

networks:
  local-network: